name: Build docker app

on:
    push:
        paths:
            - src/**

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests datetime pathlib pandas dvc dvc[s3]
          
      - name: Configure DVC Remote and pull
        run: |
          dvc remote add origin s3://dvc -f
          dvc remote modify origin endpointurl https://dagshub.com/CesarMitja/IIS_pro.s3
          dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
          dvc pull --force


      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cesi212314/project_service:latest
      - name: Build and push UI Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/client/real-estate-prediction
          file: ./src/client/real-estate-prediction/Dockerfile
          push: true
          tags: cesi212314/project_client:latest