name: MLflow App

on:
    push:
        paths:
            - data/**

jobs:
  mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dvc dvc[s3] mlflow dagshub onnx

      - name: Set up DVC and MLflow Environment
        run: |
          dvc remote add origin s3://dvc -f
          dvc remote modify origin endpointurl https://dagshub.com/CesarMitja/IIS_pro.s3
          dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
          dvc remote default origin
          dvc pull -f

      - name: Run MLflow script
        run: python src/model/Train.py
    
      - name: Run MLflow script2
        run: python src/model/Train_rent.py

