name: Python app

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main  

jobs:
    scrape:
        runs-on: ubuntu-latest
      
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup git
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
      
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install selenium webdriver-manager selenium_stealth

            - name: Install Chrome
              run: |
                sudo apt-get update
                sudo apt-get install -y wget software-properties-common apt-transport-https
                wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
                sudo apt-get update
                sudo apt-get install -y google-chrome-stable
            
            - name: Install ChromeDriver
              run: |
                CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+")
                echo "Detected Chrome version: $CHROME_VERSION"
                DRIVER_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION"
                DRIVER_VERSION=$(wget -qO- "$DRIVER_URL")
                if [[ -z "$DRIVER_VERSION" ]]; then
                  echo "No driver version found for Chrome $CHROME_VERSION, falling back to compatible version"
                  DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
                fi
                echo "Detected Driver version: $DRIVER_VERSION"
                wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" || { echo "Failed to download ChromeDriver."; exit 1; }
                unzip chromedriver_linux64.zip -d /usr/local/bin/ || { echo "Failed to unzip ChromeDriver."; exit 1; }
                chmod +x /usr/local/bin/chromedriver
                echo "ChromeDriver installed successfully."
                
            - name: Run scraper
              run: python src/data/fetch.py
            
            - name: Add data with GIT
              run: |
                git add .
                git commit -m "Update data" -a || echo "No changes to commit"
                git push